<a href="https://colab.research.google.com/github/Mayank2225/Machine-Learning-Application-for-Mechanical-Engineering/blob/main/NumPy_210598_Mayank_Singh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
oned=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
twod=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
threed=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print(oned.ndim)
print(oned.dtype)
print(type(oned))


1
int64
<class 'numpy.ndarray'>


In [ ]:
# Attributes of 2-dimensional array
print(twod.ndim)
print(twod.dtype)
print(type(twod))

2
int64
<class 'numpy.ndarray'>


In [ ]:
# Attributes of 3-dimensional array
print(threed.ndim)
print(threed.dtype)
print(type(threed))

3
int64
<class 'numpy.ndarray'>


In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
twod=np.array([[1,2,3],[4,5,6]])
df= pd.DataFrame(twod)
print(df)



   0  1  2
0  1  2  3
1  4  5  6


In [ ]:
# Create an array of shape (10, 2) with only ones
arr1=np.array([[1,1],[1,1],[1,1],[1,1],[1,1],[1,1],[1,1],[1,1],[1,1],[1,1]])

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
arr2=np.array([[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]]])

In [ ]:
# Create an array within a range of 0 and 100 with step 3
print(np.arange(0,100,3))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
from numpy import random
a=random.randint(10,size=(7,2))

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
b=random.rand(3,5)

In [ ]:
# Set the random seed to 42
random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
c=random.randint(10,size=(4,6))

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

the numbera are same because we set the the seed value.

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
bt=random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created

In [ ]:
# Find the 0'th index of the latest array you created
print(bt[0,0])

9


In [ ]:
# Get the first 2 rows of latest array you created
print(bt[0:2,0:7])

[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]]


In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
print(bt[0:2,0:2])

[[9 1]
 [5 3]]


In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
n=random.randint(10, size=(3,5))
b=np.array([[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]])

In [ ]:
# Add the two arrays together
k=np.add(n,b)

In [ ]:
# Create another array of ones of shape (5, 3)
t=np.array([[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1]])

In [ ]:
# Try add the array of ones and the other most recent array together
print(np.add(k,t))

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
f=np.array([[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]])

In [ ]:
# Subtract the new array of ones from the other most recent array
s=np.subtract(f,k)
print(s)

[[-5 -6 -1  1 -2]
 [ 0 -6 -2  0 -4]
 [-4 -8 -2 -4  0]]


In [ ]:
# Multiply the ones array with the latest array
m=np.multiply(f,s)
print(m)

[[-5 -6 -1  1 -2]
 [ 0 -6 -2  0 -4]
 [-4 -8 -2 -4  0]]


In [ ]:
# Take the latest array to the power of 2 using '**'
z=m**2
print(z)

[[25 36  1  1  4]
 [ 0 36  4  0 16]
 [16 64  4 16  0]]


In [ ]:
# Do the same thing with np.square()
print(np.square(m))


[[25 36  1  1  4]
 [ 0 36  4  0 16]
 [16 64  4 16  0]]


In [ ]:
# Find the mean of the latest array using np.mean()
print(np.mean(z))

14.866666666666667


In [ ]:
# Find the maximum of the latest array using np.max()
print(np.max(z))

64


In [ ]:
# Find the minimum of the latest array using np.min()
print(np.min(z))

0


In [ ]:
# Find the standard deviation of the latest array
print(np.std(z))

17.917837171067518


In [ ]:
# Find the variance of the latest array
print(np.var(z))

321.0488888888889


In [ ]:
# Reshape the latest array to (3, 5, 1)
newz=z.reshape(3,5,1)

In [ ]:
# Transpose the latest array
print(newz.transpose)

<built-in method transpose of numpy.ndarray object at 0x7efbe5fd12d0>


What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1=random.randint(10, size=(3,3))
a2=random.randint(10, size=(3,2))

In [ ]:
# Perform a dot product on the two newest arrays you created
print(np.dot(a1,a2))

[[ 88 117]
 [100 123]
 [ 89 127]]


In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a3=random.randint(10, size=(4,3))
a4=random.randint(10, size=(4,3))

In [ ]:
# Perform a dot product on the two newest arrays you created
print(np.dot(a3,a4))

ValueError: ignored

It doesn't work. How would you fix it?

we take transpose of any one of the array

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
newa3=a3.transpose()
print(np.dot(newa3,a4))

[[128  90 128]
 [184  91 151]
 [ 42  14  40]]


In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a5=random.randint(10, size=(4,3))
a6=random.randint(10, size=(4,3))

In [ ]:
# Compare the two arrays with '>'
print(a5>a6)

[[ True  True False]
 [False False False]
 [False False False]
 [False  True False]]


What happens when you compare the arrays with `>`?

it gives a 2-D array with values true and false for the given command

In [ ]:
# Compare the two arrays with '>='
print(a5>=a6)

[[ True  True False]
 [False False False]
 [False False False]
 [False  True False]]


In [ ]:
# Find which elements of the first array are greater than 7
x1=np.where(a5>7)
print(x1)

(array([], dtype=int64), array([], dtype=int64))


In [ ]:
# Which parts of each array are equal? (try using '==')
x2=np.where(a5==a6)
print(x2)

(array([], dtype=int64), array([], dtype=int64))


In [ ]:
# Sort one of the arrays you just created in ascending order
a51=np.sort(a5)
print(a51)

[[6 6 7]
 [2 4 7]
 [0 2 5]
 [2 2 4]]


In [ ]:
# Sort the indexes of one of the arrays you just created


In [ ]:
# Find the index with the maximum value in one of the arrays you've created
y1=np.max(a51)
y2=np.where(a51==y1)
print(y2)

(array([0, 1]), array([2, 2]))


In [ ]:
# Find the index with the minimum value in one of the arrays you've created
y3=np.min(a51)
y4=np.where(a51==y3)
print(y4)

(array([2]), array([0]))


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print(np.argmax(a5,axis=1))

[2 2 0 1]


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print(np.argmax(a5,axis=0))

[0 0 0]


In [ ]:
# Create an array of normally distributed random numbers
a7=random.normal(size=10)

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a8=np.arange(1,100,10)
print(a8)

[ 1 11 21 31 41 51 61 71 81 91]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.